version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/backend/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/database/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/frontend/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/gateway/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

      
