spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: frontend
          uri: http://localhost:8081
          predicates:
            - Path=/**
        - id: backend
          uri: http://localhost:8080/api/v1
          predicates:
            - Path=/api/v1/**
server:
  port: 80
