name: Java CI with Maven

on:
  push:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  frontend-build:
    name: Frontend Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build
      run: mvn -B package --file frontend/pom.xml
  backend-build:
    name: Backend Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build
      run: mvn -B package --file backend/pom.xml
  database-build:
    name: Database Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build
      run: mvn -B package --file database/pom.xml
  gateway-build:
    name: Gateway Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build
      run: mvn -B package --file gateway/pom.xml
    